arch:
  - amd64
  - ppc64le
language: c
dist: bionic
sudo: required

# install build dependencies
before_install:
  - sudo apt-get install cmake libgtk-3-dev libappindicator3-dev libxi-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
